# RNN - Befor start NLP ADVANCE Concepts like - Open AI,Word embedding ,adv.part-2 is base on RNN.

## RNN : Recural Neural Network

RNN >> is Neural network which is designed for sequential data.

Sequential data>> text,audio,time series,DNA sequence.

In [128]:
# ANN >> work on Structured and tabular data,images.
#CNN >>

In [129]:
# applications where use RNN:
# 1) sentiment analysis
# 2) chatbot
# 3) langauge translataion
# 4) word prediction
# 5) stock market prediction
# 6) weather forcasting
# 7) alexa /siri  Speech recognition
# 8) Text generation

# Types of Architectures of RNN : 

1. One to one architecture. >> imageclassification>>one image > one label.
2. One to many >> single image >>caption>(it means we got may captions means outputs.)
3. Many to one >> Sentiment analysis--eg many word in review >> and got good o/p.
4. Many to Many >> Language Translation.(we can conver many words to many words)

## Types Of RNN :   RNN remember past input's or data.

1. Simple RNN .>> Vanishing gradient,>> can not handles long text depenancies.
        (eg.it not handle long text or words at a time  bcoz it dont have memory)

2. LSTM.(Long shot term memory) >> Uses memory > so it handles long dependencies.
                     (eg. it have long memory so it will work on sequential                                data and long text and understand meaning.)

3. GRU.( Gated recurrent Unit)>>

In [130]:
# RNN -> It is Neural Network with Memory.

# Example : 1.Simple RNN :

In [131]:
# Eg. 1 ) Many to one :

In [132]:
# iNput >> 1,2,3,4
#output >> 5

In [133]:
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense,SimpleRNN
from tensorflow.keras.models import Sequential

In [134]:
# we are going to work on User data:

In [135]:
X= np.array([[1,2,3,4]])
y= np.array([5])

In [136]:
#Step 1 : input reshape

In [137]:
# cnn >> 1,256,256,3
# RNN >> 1,4,1 >> it means 1 3D aray that have 4 rows and  1 column. because it is many to one

In [138]:
X_new= X.reshape((1,4,1))

In [139]:
X_new

array([[[1],
        [2],
        [3],
        [4]]])

In [140]:
y

array([5])

In [141]:
# scaling : but here scaling not required.

In [142]:
# step 2 : Model Training.

In [143]:
 model = Sequential([
       SimpleRNN(10,activation='relu',input_shape=(4,1)), #sirst input layer & 10 is no.of units.
       Dense(1)                                          # here no need activation func.
  ])

d:\ITVedant\itv-AiML_projects\Restaurant-Reviews-Predictions-With-RNN_Lstm\Project_env\lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [144]:
#here we use loss = mse >> becuz it is regression or countinued data example. 
#& NO need accuracy in this example..becoz here only single o/p
model.compile(optimizer='adam',loss='mse')

In [145]:
model.fit(X_new,y,epochs=193)

Epoch 1/193

1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - loss: 1.2942
Epoch 2/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 1.1429
Epoch 3/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - loss: 1.0020
Epoch 4/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - loss: 0.8716
Epoch 5/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 0.7516
Epoch 6/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step - loss: 0.6419
Epoch 7/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step - loss: 0.5424
Epoch 8/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 0.4528
Epoch 9/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - loss: 0.3729
Epoch 10/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - loss: 0.3024
Epoch 11/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 243ms/step - loss: 0.2408
Epoch 12/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - loss: 0.1878
Epoch 13/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 0.1428
Epoch 14/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.1052
Epoch 15/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 0.0746
Epoch 16/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 0.0503
Epoch 17/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - loss: 0.0317
Epoch 18/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 0.0180
Epoch 19/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step - loss: 0.0087
Epoch 20/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 374ms/step - loss: 0.0031
Epoch 21/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - loss: 4.1087e-04
Epoch 22/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 326ms/step - loss: 1.3936e-04
Epoch 23/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0017
Epoch 24/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0045
Epoch 25/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 0.0081
Epoch 26/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0122
Epoch 27/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - loss: 0.0163
Epoch 28/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 0.0198
Epoch 29/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - loss: 0.0227
Epoch 30/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 0.0248
Epoch 31/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - loss: 0.0264
Epoch 32/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0274
Epoch 33/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0276
Epoch 34/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 0.0271
Epoch 35/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0260
Epoch 36/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 0.0244
Epoch 37/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0225
Epoch 38/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0202
Epoch 39/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - loss: 0.0178
Epoch 40/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0153
Epoch 41/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0128
Epoch 42/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0105
Epoch 43/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0083
Epoch 44/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0064
Epoch 45/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0047
Epoch 46/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0032
Epoch 47/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0021
Epoch 48/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0012
Epoch 49/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 6.1491e-04
Epoch 50/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - loss: 2.2895e-04
Epoch 51/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 3.7562e-05
Epoch 52/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - loss: 4.5798e-06
Epoch 53/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 9.2631e-05
Epoch 54/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 2.6511e-04
Epoch 55/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 4.8795e-04
Epoch 56/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 7.3075e-04
Epoch 57/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 9.6797e-04
Epoch 58/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0012
Epoch 59/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0014
Epoch 60/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 392ms/step - loss: 0.0015
Epoch 61/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.0015
Epoch 62/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - loss: 0.0016
Epoch 63/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 727ms/step - loss: 0.0015
Epoch 64/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - loss: 0.0014
Epoch 65/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 341ms/step - loss: 0.0013
Epoch 66/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 360ms/step - loss: 0.0012
Epoch 67/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 369ms/step - loss: 0.0010
Epoch 68/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 8.5164e-04
Epoch 69/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step - loss: 6.8936e-04
Epoch 70/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 5.3650e-04
Epoch 71/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 3.9868e-04
Epoch 72/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - loss: 2.7997e-04
Epoch 73/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 367ms/step - loss: 1.8260e-04
Epoch 74/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 1.0742e-04
Epoch 75/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 217ms/step - loss: 5.3742e-05
Epoch 76/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 1.9831e-05
Epoch 77/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 3.1262e-06
Epoch 78/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 4.8202e-07
Epoch 79/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 242ms/step - loss: 8.4967e-06
Epoch 80/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - loss: 2.3749e-05
Epoch 81/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - loss: 4.3032e-05
Epoch 82/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - loss: 6.3488e-05
Epoch 83/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - loss: 8.2775e-05
Epoch 84/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 9.9063e-05
Epoch 85/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - loss: 1.1119e-04
Epoch 86/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 241ms/step - loss: 1.1846e-04
Epoch 87/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - loss: 1.2073e-04
Epoch 88/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - loss: 1.1826e-04
Epoch 89/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - loss: 1.1165e-04
Epoch 90/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 1.0172e-04
Epoch 91/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 8.9446e-05
Epoch 92/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 327ms/step - loss: 7.5813e-05
Epoch 93/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 6.1760e-05
Epoch 94/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - loss: 4.8129e-05
Epoch 95/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 3.5624e-05
Epoch 96/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - loss: 2.4730e-05
Epoch 97/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 488ms/step - loss: 1.5789e-05
Epoch 98/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 247ms/step - loss: 8.9387e-06
Epoch 99/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - loss: 4.1612e-06
Epoch 100/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 438ms/step - loss: 1.2988e-06
Epoch 101/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 371ms/step - loss: 9.0819e-08
Epoch 102/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 2.1394e-07
Epoch 103/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 1.3108e-06
Epoch 104/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step - loss: 3.0209e-06
Epoch 105/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 319ms/step - loss: 5.0099e-06
Epoch 106/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 328ms/step - loss: 6.9961e-06
Epoch 107/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 8.7459e-06
Epoch 108/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - loss: 1.0100e-05
Epoch 109/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 1.0961e-05
Epoch 110/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - loss: 1.1291e-05
Epoch 111/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 1.1110e-05
Epoch 112/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 1.0486e-05
Epoch 113/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 9.5004e-06
Epoch 114/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 8.2593e-06
Epoch 115/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 237ms/step - loss: 6.8856e-06
Epoch 116/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 5.4771e-06
Epoch 117/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 4.1340e-06
Epoch 118/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 2.9239e-06
Epoch 119/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 1.9056e-06
Epoch 120/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 1.1065e-06
Epoch 121/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - loss: 5.3435e-07
Epoch 122/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - loss: 1.8010e-07
Epoch 123/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 365ms/step - loss: 1.8990e-08
Epoch 124/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step - loss: 1.5489e-08
Epoch 125/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 1.2824e-07
Epoch 126/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 3.1499e-07
Epoch 127/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 5.3644e-07
Epoch 128/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - loss: 7.5564e-07
Epoch 129/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - loss: 9.4995e-07
Epoch 130/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - loss: 1.0935e-06
Epoch 131/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 1.1799e-06
Epoch 132/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 1.2059e-06
Epoch 133/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - loss: 1.1716e-06
Epoch 134/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 1.0885e-06
Epoch 135/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - loss: 9.6488e-07
Epoch 136/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 391ms/step - loss: 8.1737e-07
Epoch 137/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 593ms/step - loss: 6.5943e-07
Epoch 138/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - loss: 5.0411e-07
Epoch 139/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step - loss: 3.6041e-07
Epoch 140/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step - loss: 2.3702e-07
Epoch 141/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 322ms/step - loss: 1.3798e-07
Epoch 142/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 6.7041e-08
Epoch 143/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - loss: 2.2993e-08
Epoch 144/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 299ms/step - loss: 2.5548e-09
Epoch 145/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step - loss: 1.7608e-09
Epoch 146/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - loss: 1.5489e-08
Epoch 147/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step - loss: 3.8595e-08
Epoch 148/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step - loss: 6.6057e-08
Epoch 149/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 349ms/step - loss: 9.2841e-08
Epoch 150/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 1.1494e-07
Epoch 151/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 1.3202e-07
Epoch 152/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - loss: 1.4047e-07
Epoch 153/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - loss: 1.4119e-07
Epoch 154/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 1.3516e-07
Epoch 155/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - loss: 1.2384e-07
Epoch 156/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 261ms/step - loss: 1.0700e-07
Epoch 157/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - loss: 8.8250e-08
Epoch 158/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 6.8531e-08
Epoch 159/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 5.0013e-08
Epoch 160/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - loss: 3.3528e-08
Epoch 161/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 1.9922e-08
Epoch 162/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 1.0027e-08
Epoch 163/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 225ms/step - loss: 3.7253e-09
Epoch 164/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - loss: 5.4592e-10
Epoch 165/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - loss: 1.1005e-10
Epoch 166/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - loss: 1.7210e-09
Epoch 167/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 208ms/step - loss: 4.6496e-09
Epoch 168/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 8.1220e-09
Epoch 169/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step - loss: 1.1820e-08
Epoch 170/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - loss: 1.4554e-08
Epoch 171/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 1.6699e-08
Epoch 172/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 1.7826e-08
Epoch 173/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 1.7826e-08
Epoch 174/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 1.6946e-08
Epoch 175/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 1.5135e-08
Epoch 176/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 252ms/step - loss: 1.2879e-08
Epoch 177/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 293ms/step - loss: 1.0510e-08
Epoch 178/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step - loss: 7.9510e-09
Epoch 179/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - loss: 5.6045e-09
Epoch 180/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - loss: 3.5527e-09
Epoch 181/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step - loss: 2.0091e-09
Epoch 182/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 711ms/step - loss: 8.4606e-10
Epoch 183/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 2.1851e-10
Epoch 184/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 9.0949e-13
Epoch 185/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 1.1005e-10
Epoch 186/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - loss: 4.6043e-10
Epoch 187/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - loss: 9.0245e-10
Epoch 188/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 1.4190e-09
Epoch 189/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step - loss: 1.8010e-09
Epoch 190/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - loss: 2.1837e-09
Epoch 191/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 2.4122e-09
Epoch 192/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 2.4122e-09
Epoch 193/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 223ms/step - loss: 2.3656e-09

In [146]:
model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 363ms/step

array([[5.000046]], dtype=float32)

In [147]:
# NOw work on New User data :

In [148]:
a=np.array([[6,7,8,9]])

In [149]:
#  : Reshape the input

In [150]:
a_new=a.reshape((1,4,1))

In [151]:
model.predict(a_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

array([[10.574869]], dtype=float32)

# Example 2. LSTM/GRU : (Many to one eg.)

In [152]:
# Pre Data work

## Case Study -1 Restaurant reviews Predictions

In [153]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import pandas as pd

# First we Chck result with Simple ML model :

In [154]:
# Step 1. Read data:

In [222]:
df=pd.read_csv('r_data.tsv',delimiter='\t')

In [223]:
df

                                                 Review  Liked
0                              Wow... Loved this place.      1
1                                    Crust is not good.      0
2             Not tasty and the texture was just nasty.      0
3     Stopped by during the late May bank holiday of...      1
4     The selection on the menu was great and so wer...      1
...                                                 ...    ...
1390                                            not bad      1
1391                                           bad tase      0
1392                                           bad food      0
1393                                          bad taste      0
1394                                        bad quality      0

[1395 rows x 2 columns]

In [224]:
df.shape

(1395, 2)

In [225]:
# Step 2. Data Cleaning :

In [226]:
df.isnull().sum()

Review    0
Liked     0
dtype: int64

In [227]:
df.dtypes

Review    object
Liked      int64
dtype: object

In [228]:
# Step 3.Text Preprocessing : 

# Lowercase,special characters,digit stopwords steming etc we have to do in preprocess

In [229]:
#NLP - NLTK packages

In [230]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import re

In [231]:
# let create stopwords list first to future:

s_list=stopwords.words('english')

In [232]:
#which u want word that remove from stopword.
s_list.remove('not')

In [233]:
len(s_list)

197

In [234]:
# then iterate all review one by one from list to array for train and understand.

In [235]:
df['Review']

0                                Wow... Loved this place.
1                                      Crust is not good.
2               Not tasty and the texture was just nasty.
3       Stopped by during the late May bank holiday of...
4       The selection on the menu was great and so wer...
                              ...
1390                                              not bad
1391                                             bad tase
1392                                             bad food
1393                                            bad taste
1394                                          bad quality
Name: Review, Length: 1395, dtype: object

In [236]:
for i in df['Review']:
    print(i)

Wow... Loved this place.
Crust is not good.
Not tasty and the texture was just nasty.
Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.
The selection on the menu was great and so were the prices.
Now I am getting angry and I want my damn pho.
Honeslty it didn't taste THAT fresh.)
The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.
The fries were great too.
A great touch.
Service was very prompt.
Would not go back.
The cashier had no care what so ever on what I had to say it still ended up being wayyy overpriced.
I tried the Cape Cod ravoli, chicken, with cranberry...mmmm!
I was disgusted because I was pretty sure that was human hair.
I was shocked because no signs indicate cash only.
Highly recommended.
Waitress was a little slow in service.
This place is not worth your time, let alone Vegas.
did not like at all.
The Burrittos Blah!
The food, amazing.
Service is also cute.
I could care less... The interior is just beautiful.
So they performed.
That's right....the red velvet cake.....ohhh this stuff is so good.
- They never brought a salad we asked for.
This hole in the wall has great Mexican street tacos, and friendly staff.
Took an hour to get our food only 4 tables in restaurant my food was Luke warm, Our sever was running around like he was totally overwhelmed.
The worst was the salmon sashimi.
Also there are combos like a burger, fries, and beer for 23 which is a decent deal.
This was like the final blow!
I found this place by accident and I could not be happier.
seems like a good quick place to grab a bite of some familiar pub food, but do yourself a favor and look elsewhere.
Overall, I like this place a lot.
The only redeeming quality of the restaurant was that it was very inexpensive.
Ample portions and good prices.
Poor service, the waiter made me feel like I was stupid every time he came to the table.
My first visit to Hiro was a delight!
Service sucks.
The shrimp tender and moist.
There is not a deal good enough that would drag me into that establishment again.
Hard to judge whether these sides were good because we were grossed out by the melted styrofoam and didn't want to eat it for fear of getting sick.
On a positive note, our server was very attentive and provided great service.
Frozen pucks of disgust, with some of the worst people behind the register.
The only thing I did like was the prime rib and dessert section.
It's too bad the food is so damn generic.
The burger is good beef, cooked just right.
If you want a sandwich just go to any Firehouse!!!!!
My side Greek salad with the Greek dressing was so tasty, and the pita and hummus was very refreshing.
We ordered the duck rare and it was pink and tender on the inside with a nice char on the outside.
He came running after us when he realized my husband had left his sunglasses on the table.
Their chow mein is so good!
They have horrible attitudes towards customers, and talk down to each one when customers don't enjoy their food.
The portion was huge!
Loved it...friendly servers, great food, wonderful and imaginative menu.
The Heart Attack Grill in downtown Vegas is an absolutely flat-lined excuse for a restaurant.
Not much seafood and like 5 strings of pasta at the bottom.
The salad had just the right amount of sauce to not over power the scallop, which was perfectly cooked.
The ripped banana was not only ripped, but petrified and tasteless.
At least think to refill my water before I struggle to wave you over for 10 minutes.
This place receives stars for their APPETIZERS!!!
The cocktails are all handmade and delicious.
We'd definitely go back here again.
We are so glad we found this place.
Great food and service, huge portions and they give a military discount.
Always a great time at Dos Gringos!
Update.....went back for a second time and it was still just as amazing
We got the food and apparently they have never heard of salt and the batter on the fish was chewy.
A great way to finish a great.
The deal included 5 tastings and 2 drinks, and Jeff went above and beyond what we expected.
- Really, really good rice, all the time.
The service was meh.
It took over 30 min to get their milkshake, which was nothing more than chocolate milk.
I guess I should have known that this place would suck, because it is inside of the Excalibur, but I didn't use my common sense.
The scallop dish is quite appalling for value as well.
2 times - Very Bad Customer Service !
The sweet potato fries were very good and seasoned well.
Today is the second time I've been to their lunch buffet and it was pretty good.
There is so much good food in Vegas that I feel cheated for wasting an eating opportunity by going to Rice and Company.
Coming here is like experiencing an underwhelming relationship where both parties can't wait for the other person to ask to break up.
walked in and the place smelled like an old grease trap and only 2 others there eating.
The turkey and roast beef were bland.
This place has it!
The pan cakes everyone are raving about taste like a sugary disaster tailored to the palate of a six year old.
I love the Pho and the spring rolls oh so yummy you have to try.
The poor batter to meat ratio made the chicken tenders very unsatisfying.
All I have to say is the food was amazing!!!
Omelets are to die for!
Everything was fresh and delicious!
In summary, this was a largely disappointing dining experience.
It's like a really sexy party in your mouth, where you're outrageously flirting with the hottest person at the party.
Never been to Hard Rock Casino before, WILL NEVER EVER STEP FORWARD IN IT AGAIN!
Best breakfast buffet!!!
say bye bye to your tip lady!
We'll never go again.
Will be back again!
Food arrived quickly!
It was not good.
On the up side, their cafe serves really good food.
Our server was fantastic and when he found out the wife loves roasted garlic and bone marrow, he added extra to our meal and another marrow to go!
The only good thing was our waiter, he was very helpful and kept the bloddy mary's coming.
Best Buffet in town, for the price you cannot beat it.
I LOVED their mussels cooked in this wine reduction, the duck was tender, and their potato dishes were delicious.
This is one of the better buffets that I have been to.
So we went to Tigerlilly and had a fantastic afternoon!
The food was delicious, our bartender was attentive and personable AND we got a great deal!
The ambience is wonderful and there is music playing.
Will go back next trip out.
Sooooo good!!
REAL sushi lovers, let's be honest - Yama is not that good.
At least 40min passed in between us ordering and the food arriving, and it wasn't that busy.
This is a really fantastic Thai restaurant which is definitely worth a visit.
Nice, spicy and tender.
Good prices.
Check it out.
It was pretty gross!
I've had better atmosphere.
Kind of hard to mess up a steak but they did.
Although I very much liked the look and sound of this place, the actual experience was a bit disappointing.
I just don't know how this place managed to served the blandest food I have ever eaten when they are preparing Indian cuisine.
Worst service to boot, but that is the least of their worries.
Service was fine and the waitress was friendly.
The guys all had steaks, and our steak loving son who has had steak at the best and worst places said it was the best steak he's ever eaten.
We thought you'd have to venture further away to get good sushi, but this place really hit the spot that night.
Host staff were, for lack of a better word, BITCHES!
Bland... Not a liking this place for a number of reasons and I don't want to waste time on bad reviewing.. I'll leave it at that...
Phenomenal food, service and ambiance.
I wouldn't return.
Definitely worth venturing off the strip for the pork belly, will return next time I'm in Vegas.
This place is way too overpriced for mediocre food.
Penne vodka excellent!
They have a good selection of food including a massive meatloaf sandwich, a crispy chicken wrap, a delish tuna melt and some tasty burgers.
The management is rude.
Delicious NYC bagels, good selections of cream cheese, real Lox with capers even.
Great Subway, in fact it's so good when you come here every other Subway will not meet your expectations.
I had a seriously solid breakfast here.
This is one of the best bars with food in Vegas.
He was extremely rude and really, there are so many other restaurants I would love to dine at during a weekend in Vegas.
My drink was never empty and he made some really great menu suggestions.
Don't do it!!!!
The waiter wasn't helpful or friendly and rarely checked on us.
My husband and I ate lunch here and were very disappointed with the food and service.
And the red curry had so much bamboo shoots and wasn't very tasty to me.
Nice blanket of moz over top but i feel like this was done to cover up the subpar food.
The bathrooms are clean and the place itself is well decorated.
The menu is always changing, food quality is going down & service is extremely slow.
The service was a little slow , considering that were served by 3 people servers so the food was coming in a slow pace.
I give it 2 thumbs down
We watched our waiter pay a lot more attention to other tables and ignore us.
My fiancé and I came in the middle of the day and we were greeted and seated right away.
This is a great restaurant at the Mandalay Bay.
We waited for forty five minutes in vain.
Crostini that came with the salad was stale.
Some highlights : Great quality nigiri here!
the staff is friendly and the joint is always clean.
this was a different cut than the piece the other day but still wonderful and tender s well as well flavored.
I ordered the Voodoo pasta and it was the first time I'd had really excellent pasta since going gluten free several years ago.
this place is good.
Unfortunately, we must have hit the bakery on leftover day because everything we ordered was STALE.
I came back today since they relocated and still not impressed.
I was seated immediately.
Their menu is diverse, and reasonably priced.
Avoid at all cost!
Restaurant is always full but never a wait.
DELICIOUS!!
This place is hands-down one of the best places to eat in the Phoenix metro area.
So don't go there if you are looking for good food...
I've never been treated so bad.
Bacon is hella salty.
We also ordered the spinach and avocado salad, the ingredients were sad and the dressing literally had zero taste.
This really is how Vegas fine dining used to be, right down to the menus handed to the ladies that have no prices listed.
The waitresses are very friendly.
Lordy, the Khao Soi is a dish that is not to be missed for curry lovers!
Everything on the menu is terrific and we were also thrilled that they made amazing accommodations for our vegetarian daughter.
Perhaps I caught them on an off night judging by the other reviews, but I'm not inspired to go back.
The service here leaves a lot to be desired.
The atmosphere is modern and hip, while maintaining a touch of coziness.
Not a weekly haunt, but definitely a place to come back to every once in a while.
We literally sat there for 20 minutes with no one asking to take our order.
The burger had absolutely no flavor - the meat itself was totally bland, the burger was overcooked and there was no charcoal flavor.
I also decided not to send it back because our waitress looked like she was on the verge of having a heart attack.
I dressed up to be treated so rudely!
It was probably dirt.
Love this place, hits the spot when I want something healthy but not lacking in quantity or flavor.
I ordered the Lemon raspberry ice cocktail which was also incredible.
The food sucked, which we expected but it sucked more than we could have imagined.
Interesting decor.
What I really like there is the crepe station.
Also were served hot bread and butter, and home made potato chips with bacon bits on top....very original and very good.
you can watch them preparing the delicious food!)
Both of the egg rolls were fantastic.
When my order arrived, one of the gyros was missing.
I had a salad with the wings, and some ice cream for dessert and left feeling quite satisfied.
I'm not really sure how Joey's was voted best hot dog in the Valley by readers of Phoenix Magazine.
The best place to go for a tasty bowl of Pho!
The live music on Fridays totally blows.
I've never been more insulted or felt disrespected.
Very friendly staff.
It is worth the drive.
I had heard good things about this place, but it exceeding every hope I could have dreamed of.
Food was great and so was the serivce!
The warm beer didn't help.
Great brunch spot.
Service is friendly and inviting.
Very good lunch spot.
I've lived here since 1979 and this was the first (and last) time I've stepped foot into this place.
The WORST EXPERIENCE EVER.
Must have been an off night at this place.
The sides are delish - mixed mushrooms, yukon gold puree, white corn - beateous.
If that bug never showed up I would have given a 4 for sure, but on the other side of the wall where this bug was climbing was the kitchen.
For about 10 minutes, we we're waiting for her salad when we realized that it wasn't coming any time soon.
My friend loved the salmon tartar.
Won't go back.
Extremely Tasty!
Waitress was good though!
Soggy and not good.
The Jamaican mojitos are delicious.
Which are small and not worth the price.
- the food is rich so order accordingly.
The shower area is outside so you can only rinse, not take a full shower, unless you don't mind being nude for everyone to see!
The service was a bit lacking.
Lobster Bisque, Bussell Sprouts, Risotto, Filet ALL needed salt and pepper..and of course there is none at the tables.
Hopefully this bodes for them going out of business and someone who can cook can come in.
It was either too cold, not enough flavor or just bad.
I loved the bacon wrapped dates.
This is an unbelievable BARGAIN!
The folks at Otto always make us feel so welcome and special.
As for the "mains," also uninspired.
This is the place where I first had pho and it was amazing!!
This wonderful experience made this place a must-stop whenever we are in town again.
If the food isn't bad enough for you, then enjoy dealing with the world's worst/annoying drunk people.
Very very fun chef.
Ordered a double cheeseburger & got a single patty that was falling apart (picture uploaded) Yeah, still sucks.
Great place to have a couple drinks and watch any and all sporting events as the walls are covered with TV's.
If it were possible to give them zero stars, they'd have it.
The descriptions said "yum yum sauce" and another said "eel sauce", yet another said "spicy mayo"...well NONE of the rolls had sauces on them.
I'd say that would be the hardest decision... Honestly, all of M's dishes taste how they are supposed to taste (amazing).
If she had not rolled the eyes we may have stayed... Not sure if we will go back and try it again.
Everyone is very attentive, providing excellent customer service.
Horrible - don't waste your time and money.
Now this dish was quite flavourful.
By this time our side of the restaurant was almost empty so there was no excuse.
(It wasn't busy either) Also, the building was FREEZING cold.
like the other reviewer said "you couldn't pay me to eat at this place again."
-Drinks took close to 30 minutes to come out at one point.
Seriously flavorful delights, folks.
Much better than the other AYCE sushi place I went to in Vegas.
The lighting is just dark enough to set the mood.
Based on the sub-par service I received and no effort to show their gratitude for my business I won't be going back.
Owner's are really great people.!
There is nothing privileged about working/eating there.
The Greek dressing was very creamy and flavorful.
Overall, I don't think that I would take my parents to this place again because they made most of the similar complaints that I silently felt too.
Now the pizza itself was good the peanut sauce was very tasty.
We had 7 at our table and the service was pretty fast.
Fantastic service here.
I as well would've given godfathers zero stars if possible.
They know how to make them here.
very tough and very short on flavor!
I hope this place sticks around.
I have been in more than a few bars in Vegas, and do not ever recall being charged for tap water.
The restaurant atmosphere was exquisite.
Good service, very clean, and inexpensive, to boot!
The seafood was fresh and generous in portion.
Plus, it's only 8 bucks.
The service was not up to par, either.
Thus far, have only visited twice and the food was absolutely delicious each time.
Just as good as when I had it more than a year ago!
For a self proclaimed coffee cafe, I was wildly disappointed.
The Veggitarian platter is out of this world!
You cant go wrong with any of the food here.
You can't beat that.
Stopped by this place while in Madison for the Ironman, very friendly, kind staff.
The chefs were friendly and did a good job.
I've had better, not only from dedicated boba tea spots, but even from Jenni Pho.
I liked the patio and the service was outstanding.
The goat taco didn't skimp on the meat and wow what FLAVOR!
I think not again
I had the mac salad and it was pretty bland so I will not be getting that again.
I went to Bachi Burger on a friend's recommendation and was not disappointed.
Service stinks here!
I waited and waited.
This place is not quality sushi, it is not a quality restaurant.
I would definitely recommend the wings as well as the pizza.
Great Pizza and Salads!
Things that went wrong: - They burned the saganaki.
We waited an hour for what was a breakfast I could have done 100 times better at home.
This place is amazing!
I hate to disagree with my fellow Yelpers, but my husband and I were so disappointed with this place.
Waited 2 hours & never got either of our pizzas as many other around us who came in later did!
Just don't know why they were so slow.
The staff is great, the food is delish, and they have an incredible beer selection.
I live in the neighborhood so I am disappointed I won't be back here, because it is a convenient location.
I didn't know pulled pork could be soooo delicious.
You get incredibly fresh fish, prepared with care.
Before I go in to why I gave a 1 star rating please know that this was my third time eating at Bachi burger before writing a review.
I love the fact that everything on their menu is worth it.
Never again will I be dining at this place!
The food was excellent and service was very good.
Good beer & drink selection and good food selection.
Please stay away from the shrimp stir fried noodles.
The potato chip order was sad... I could probably count how many chips were in that box and it was probably around 12.
Food was really boring.
Good Service-check!
This greedy corporation will NEVER see another dime from me!
Will never, ever go back.
As much as I'd like to go back, I can't get passed the atrocious service and will never return.
In the summer, you can dine in a charming outdoor patio - so very delightful.
I did not expect this to be so good!
Fantastic food!
She ordered a toasted English muffin that came out untoasted.
The food was very good.
Never going back.
Great food for the price, which is very high quality and house made.
The bus boy on the other hand was so rude.
By this point, my friends and I had basically figured out this place was a joke and didn't mind making it publicly and loudly known.
Back to good BBQ, lighter fare, reasonable pricing and tell the public they are back to the old ways.
And considering the two of us left there very full and happy for about $20, you just can't go wrong.
All the bread is made in-house!
The only downside is the service.
Also, the fries are without a doubt the worst fries I've ever had.
Service was exceptional and food was a good as all the reviews.
A couple of months later, I returned and had an amazing meal.
Favorite place in town for shawarrrrrrma!!!!!!
The black eyed peas and sweet potatoes... UNREAL!

In [237]:
# now use nlp concepts preprocessing steps:

In [238]:
corpus=[]
for i in df['Review']:
    mystr=i.lower()          #for lowercase convert 1st step.
    newstr=re.sub(r'[^a-zA-Z\s]','',mystr) # remove special character's/digit.
    list1=word_tokenize(newstr)  # use tokenizer for split each word.
    list2=[ i for i in list1 if i not in s_list]   # use this for remove stopwords.
    ps=PorterStemmer()                          # Use Stemming (last word removing unnecesry.
    list3=[ps.stem(i) for i in list2] #stemming
    final=' '.join(list3)         # for convert list in to  string structure.
    corpus.append(final)

In [239]:
corpus

['wow love place',
 'crust not good',
 'not tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti didnt tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would not go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberrymmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place not worth time let alon vega',
 'not like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'that rightth red velvet cakeohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow',
 'found place accid could not happier',
 'seem like good quick place grab bite familiar pub food favor look elsewher',
 'overal like place lot',
 'redeem qualiti restaur inexpens',
 'ampl portion good price',
 'poor servic waiter made feel like stupid everi time came tabl',
 'first visit hiro delight',
 'servic suck',
 'shrimp tender moist',
 'not deal good enough would drag establish',
 'hard judg whether side good gross melt styrofoam didnt want eat fear get sick',
 'posit note server attent provid great servic',
 'frozen puck disgust worst peopl behind regist',
 'thing like prime rib dessert section',
 'bad food damn gener',
 'burger good beef cook right',
 'want sandwich go firehous',
 'side greek salad greek dress tasti pita hummu refresh',
 'order duck rare pink tender insid nice char outsid',
 'came run us realiz husband left sunglass tabl',
 'chow mein good',
 'horribl attitud toward custom talk one custom dont enjoy food',
 'portion huge',
 'love itfriendli server great food wonder imagin menu',
 'heart attack grill downtown vega absolut flatlin excus restaur',
 'not much seafood like string pasta bottom',
 'salad right amount sauc not power scallop perfectli cook',
 'rip banana not rip petrifi tasteless',
 'least think refil water struggl wave minut',
 'place receiv star appet',
 'cocktail handmad delici',
 'wed definit go back',
 'glad found place',
 'great food servic huge portion give militari discount',
 'alway great time do gringo',
 'updatew back second time still amaz',
 'got food appar never heard salt batter fish chewi',
 'great way finish great',
 'deal includ tast drink jeff went beyond expect',
 'realli realli good rice time',
 'servic meh',
 'took min get milkshak noth chocol milk',
 'guess known place would suck insid excalibur didnt use common sens',
 'scallop dish quit appal valu well',
 'time bad custom servic',
 'sweet potato fri good season well',
 'today second time ive lunch buffet pretti good',
 'much good food vega feel cheat wast eat opportun go rice compani',
 'come like experienc underwhelm relationship parti cant wait person ask break',
 'walk place smell like old greas trap other eat',
 'turkey roast beef bland',
 'place',
 'pan cake everyon rave tast like sugari disast tailor palat six year old',
 'love pho spring roll oh yummi tri',
 'poor batter meat ratio made chicken tender unsatisfi',
 'say food amaz',
 'omelet die',
 'everyth fresh delici',
 'summari larg disappoint dine experi',
 'like realli sexi parti mouth your outrag flirt hottest person parti',
 'never hard rock casino never ever step forward',
 'best breakfast buffet',
 'say bye bye tip ladi',
 'well never go',
 'back',
 'food arriv quickli',
 'not good',
 'side cafe serv realli good food',
 'server fantast found wife love roast garlic bone marrow ad extra meal anoth marrow go',
 'good thing waiter help kept bloddi mari come',
 'best buffet town price not beat',
 'love mussel cook wine reduct duck tender potato dish delici',
 'one better buffet',
 'went tigerlilli fantast afternoon',
 'food delici bartend attent person got great deal',
 'ambienc wonder music play',
 'go back next trip',
 'sooooo good',
 'real sushi lover let honest yama not good',
 'least min pass us order food arriv wasnt busi',
 'realli fantast thai restaur definit worth visit',
 'nice spici tender',
 'good price',
 'check',
 'pretti gross',
 'ive better atmospher',
 'kind hard mess steak',
 'although much like look sound place actual experi bit disappoint',
 'dont know place manag serv blandest food ever eaten prepar indian cuisin',
 'worst servic boot least worri',
 'servic fine waitress friendli',
 'guy steak steak love son steak best worst place said best steak he ever eaten',
 'thought youd ventur away get good sushi place realli hit spot night',
 'host staff lack better word bitch',
 'bland not like place number reason dont want wast time bad review ill leav',
 'phenomen food servic ambianc',
 'wouldnt return',
 'definit worth ventur strip pork belli return next time im vega',
 'place way overpr mediocr food',
 'penn vodka excel',
 'good select food includ massiv meatloaf sandwich crispi chicken wrap delish tuna melt tasti burger',
 'manag rude',
 'delici nyc bagel good select cream chees real lox caper even',
 'great subway fact good come everi subway not meet expect',
 'serious solid breakfast',
 'one best bar food vega',
 'extrem rude realli mani restaur would love dine weekend vega',
 'drink never empti made realli great menu suggest',
 'dont',
 'waiter wasnt help friendli rare check us',
 'husband ate lunch disappoint food servic',
 'red curri much bamboo shoot wasnt tasti',
 'nice blanket moz top feel like done cover subpar food',
 'bathroom clean place well decor',
 'menu alway chang food qualiti go servic extrem slow',
 'servic littl slow consid serv peopl server food come slow pace',
 'give thumb',
 'watch waiter pay lot attent tabl ignor us',
 'fianc came middl day greet seat right away',
 'great restaur mandalay bay',
 'wait forti five minut vain',
 'crostini came salad stale',
 'highlight great qualiti nigiri',
 'staff friendli joint alway clean',
 'differ cut piec day still wonder tender well well flavor',
 'order voodoo pasta first time id realli excel pasta sinc go gluten free sever year ago',
 'place good',
 'unfortun must hit bakeri leftov day everyth order stale',
 'came back today sinc reloc still not impress',
 'seat immedi',
 'menu divers reason price',
 'avoid cost',
 'restaur alway full never wait',
 'delici',
 'place handsdown one best place eat phoenix metro area',
 'dont go look good food',
 'ive never treat bad',
 'bacon hella salti',
 'also order spinach avocado salad ingredi sad dress liter zero tast',
 'realli vega fine dine use right menu hand ladi price list',
 'waitress friendli',
 'lordi khao soi dish not miss curri lover',
 'everyth menu terrif also thrill made amaz accommod vegetarian daughter',
 'perhap caught night judg review im not inspir go back',
 'servic leav lot desir',
 'atmospher modern hip maintain touch cozi',
 'not weekli haunt definit place come back everi',
 'liter sat minut one ask take order',
 'burger absolut flavor meat total bland burger overcook charcoal flavor',
 'also decid not send back waitress look like verg heart attack',
 'dress treat rude',
 'probabl dirt',
 'love place hit spot want someth healthi not lack quantiti flavor',
 'order lemon raspberri ice cocktail also incred',
 'food suck expect suck could imagin',
 'interest decor',
 'realli like crepe station',
 'also serv hot bread butter home made potato chip bacon bit topveri origin good',
 'watch prepar delici food',
 'egg roll fantast',
 'order arriv one gyro miss',
 'salad wing ice cream dessert left feel quit satisfi',
 'im not realli sure joey vote best hot dog valley reader phoenix magazin',
 'best place go tasti bowl pho',
 'live music friday total blow',
 'ive never insult felt disrespect',
 'friendli staff',
 'worth drive',
 'heard good thing place exceed everi hope could dream',
 'food great serivc',
 'warm beer didnt help',
 'great brunch spot',
 'servic friendli invit',
 'good lunch spot',
 'ive live sinc first last time ive step foot place',
 'worst experi ever',
 'must night place',
 'side delish mix mushroom yukon gold pure white corn beateou',
 'bug never show would given sure side wall bug climb kitchen',
 'minut wait salad realiz wasnt come time soon',
 'friend love salmon tartar',
 'wont go back',
 'extrem tasti',
 'waitress good though',
 'soggi not good',
 'jamaican mojito delici',
 'small not worth price',
 'food rich order accordingli',
 'shower area outsid rins not take full shower unless dont mind nude everyon see',
 'servic bit lack',
 'lobster bisqu bussel sprout risotto filet need salt pepperand cours none tabl',
 'hope bode go busi someon cook come',
 'either cold not enough flavor bad',
 'love bacon wrap date',
 'unbeliev bargain',
 'folk otto alway make us feel welcom special',
 'main also uninspir',
 'place first pho amaz',
 'wonder experi made place muststop whenev town',
 'food isnt bad enough enjoy deal world worstannoy drunk peopl',
 'fun chef',
 'order doubl cheeseburg got singl patti fall apart pictur upload yeah still suck',
 'great place coupl drink watch sport event wall cover tv',
 'possibl give zero star theyd',
 'descript said yum yum sauc anoth said eel sauc yet anoth said spici mayowel none roll sauc',
 'id say would hardest decis honestli ms dish tast suppos tast amaz',
 'not roll eye may stay not sure go back tri',
 'everyon attent provid excel custom servic',
 'horribl dont wast time money',
 'dish quit flavour',
 'time side restaur almost empti excus',
 'wasnt busi either also build freez cold',
 'like review said couldnt pay eat place',
 'drink took close minut come one point',
 'serious flavor delight folk',
 'much better ayc sushi place went vega',
 'light dark enough set mood',
 'base subpar servic receiv effort show gratitud busi wont go back',
 'owner realli great peopl',
 'noth privileg working',
 'greek dress creami flavor',
 'overal dont think would take parent place made similar complaint silent felt',
 'pizza good peanut sauc tasti',
 'tabl servic pretti fast',
 'fantast servic',
 'well wouldv given godfath zero star possibl',
 'know make',
 'tough short flavor',
 'hope place stick around',
 'bar vega not ever recal charg tap water',
 'restaur atmospher exquisit',
 'good servic clean inexpens boot',
 'seafood fresh gener portion',
 'plu buck',
 'servic not par either',
 'thu far visit twice food absolut delici time',
 'good year ago',
 'self proclaim coffe cafe wildli disappoint',
 'veggitarian platter world',
 'cant go wrong food',
 'cant beat',
 'stop place madison ironman friendli kind staff',
 'chef friendli good job',
 'ive better not dedic boba tea spot even jenni pho',
 'like patio servic outstand',
 'goat taco didnt skimp meat wow flavor',
 'think not',
 'mac salad pretti bland not get',
 'went bachi burger friend recommend not disappoint',
 'servic stink',
 'wait wait',
 'place not qualiti sushi not qualiti restaur',
 'would definit recommend wing well pizza',
 'great pizza salad',
 'thing went wrong burn saganaki',
 'wait hour breakfast could done time better home',
 'place amaz',
 'hate disagre fellow yelper husband disappoint place',
 'wait hour never got either pizza mani around us came later',
 'dont know slow',
 'staff great food delish incred beer select',
 'live neighborhood disappoint wont back conveni locat',
 'didnt know pull pork could soooo delici',
 'get incred fresh fish prepar care',
 'go gave star rate pleas know third time eat bachi burger write review',
 'love fact everyth menu worth',
 'never dine place',
 'food excel servic good',
 'good beer drink select good food select',
 'pleas stay away shrimp stir fri noodl',
 'potato chip order sad could probabl count mani chip box probabl around',
 'food realli bore',
 'good servicecheck',
 'greedi corpor never see anoth dime',
 'never ever go back',
 'much id like go back cant get pass atroci servic never return',
 'summer dine charm outdoor patio delight',
 'not expect good',
 'fantast food',
 'order toast english muffin came untoast',
 'food good',
 'never go back',
 'great food price high qualiti hous made',
 'bu boy hand rude',
 'point friend basic figur place joke didnt mind make publicli loudli known',
 'back good bbq lighter fare reason price tell public back old way',
 'consid two us left full happi cant go wrong',
 'bread made inhous',
 'downsid servic',
 'also fri without doubt worst fri ive ever',
 'servic except food good review',
 'coupl month later return amaz meal',
 'favorit place town shawarrrrrrma',
 'black eye pea sweet potato unreal',
 'wont disappoint',
 'could serv vinaigrett may make better overal dish still good',
 'go far mani place ive never seen restaur serv egg breakfast especi',
 'mom got home immedi got sick bite salad',
 'server not pleasant deal dont alway honor pizza hut coupon',
 'truli unbeliev good glad went back',
 'fantast servic pleas atmospher',
 'everyth gross',
 'love place',
 'great servic food',
 'first bathroom locat dirti seat cover not replenish plain yucki',
 'burger got gold standard burger kind disappoint',
 'omg food delicioso',
 'noth authent place',
 'spaghetti noth special whatsoev',
 'dish salmon best great',
 'veget fresh sauc feel like authent thai',
 'worth drive tucson',
 'select probabl worst ive seen vegasther none',
 'pretti good beer select',
 'place like chipotl better',
 'classywarm atmospher fun fresh appet succul steak basebal steak',
 'star brick oven bread app',
 'eaten multipl time time food delici',
 'sat anoth ten minut final gave left',
 'terribl',
 'everyon treat equal special',
 'shouldnt take min pancak egg',
 'delici',
 'good side staff genuin pleasant enthusiast real treat',
 'sadli gordon ramsey steak place shall sharpli avoid next trip vega',
 'alway even wonder food delici',
 'best fish ive ever life',
 'bathroom next door nice',
 'buffet small food offer bland',
 'outstand littl restaur best food ever tast',
 'pretti cool would say',
 'definit turn doubt ill back unless someon els buy',
 'server great job handl larg rowdi tabl',
 'find wast food despic wasnt food',
 'wife lobster bisqu soup lukewarm',
 'would come back sushi crave vega',
 'staff great ambianc great',
 'deserv star',
 'left stomach ach felt sick rest day',
 'drop ball',
 'dine space tini elegantli decor comfort',
 'custom order way youd like usual eggplant green bean stir fri love',
 'bean rice mediocr best',
 'best taco town far',
 'took back money got outta',
 'interest part town place amaz',
 'rude inconsider manag',
 'staff not friendli wait time serv horribl one even say hi first minut',
 'wont back',
 'great dinner',
 'servic outshin definit recommend halibut',
 'food terribl',
 'never ever go back told mani peopl happen',
 'dont recommend unless car break front starv',
 'come back everi time im vega',
 'place deserv one star food',
 'disgrac',
 'def come back bowl next time',
 'want healthi authent ethic food tri place',
 'continu come ladi night andddd date night highli recommend place anyon area',
 'sever time past experi alway great',
 'walk away stuf happi first vega buffet experi',
 'servic excel price pretti reason consid vega locat insid crystal shop mall aria',
 'summar food incred nay transcend noth bring joy quit like memori pneumat condiment dispens',
 'im probabl one peopl ever go ian not like',
 'kid pizza alway hit lot great side dish option kiddo',
 'servic perfect famili atmospher nice see',
 'cook perfect servic impecc',
 'one simpli disappoint',
 'overal disappoint qualiti food bouchon',
 'dont account know im get screw',
 'great place eat remind littl mom pop shop san francisco bay area',
 'today first tast buldogi gourmet hot dog tell ever thought possibl',
 'left frustrat',
 'ill definit soon',
 'food realli good got full petti fast',
 'servic fantast',
 'total wast time',
 'dont know kind best ice tea',
 'come hungri leav happi stuf',
 'servic give star',
 'assur wont disappoint',
 'take littl bad servic food suck',
 'gave tri eat crust teeth still sore',
 'complet gross',
 'realli enjoy eat',
 'first time go think quickli becom regular',
 'server nice even though look littl overwhelm need stay profession friendli end',
 'dinner companion told meeveryth fresh nice textur tast',
 'ground right next tabl larg smear beensteppedinandtrackedeverywher pile green bird poop',
 'furthermor cant even find hour oper websit',
 'weve tri like place time think done',
 'mistak',
 'complaint',
 'serious good pizza im expertconnisseur topic',
 'waiter jerk',
 'strike want rush',
 'nicest restaur owner ive ever come across',
 'never come',
 'love biscuit',
 'servic quick friendli',
 'order appet took minut pizza anoth minut',
 'absolutley fantast',
 'huge awkward lb piec cow th gristl fat',
 'definit come back',
 'like steiner dark feel like bar',
 'wow spici delici',
 'your not familiar check',
 'ill take busi dinner dollar elsewher',
 'id love go back',
 'anyway fs restaur wonder breakfastlunch',
 'noth special',
 'day week differ deal delici',
 'not mention combin pear almond bacon big winner',
 'not back',
 'sauc tasteless',
 'food delici spici enough sure ask spicier prefer way',
 'ribey steak cook perfectli great mesquit flavor',
 'dont think well go back anytim soon',
 'food gooodd',
 'far sushi connoisseur definit tell differ good food bad food certainli bad food',
 'insult',
 'last time lunch bad',
 'chicken wing contain driest chicken meat ever eaten',
 'food good enjoy everi mouth enjoy relax venu coupl small famili group etc',
 'nargil think great',
 'best tater tot southwest',
 'love place',
 'definit not worth paid',
 'vanilla ice cream creami smooth profiterol choux pastri fresh enough',
 'im az time new spot',
 'manag worst',
 'insid realli quit nice clean',
 'food outstand price reason',
 'dont think ill run back carli anytim soon food',
 'due fact took minut acknowledg anoth minut get foodand kept forget thing',
 'love margarita',
 'first vega buffet not disappoint',
 'good though',
 'one note ventil could use upgrad',
 'great pork sandwich',
 'dont wast time',
 'total letdown would much rather go camelback flower shop cartel coffe',
 'third chees friend burger cold',
 'enjoy pizza brunch',
 'steak well trim also perfectli cook',
 'group claim would handl us beauti',
 'love',
 'ask bill leav without eat didnt bring either',
 'place jewel la vega exactli ive hope find nearli ten year live',
 'seafood limit boil shrimp crab leg crab leg definit not tast fresh',
 'select food not best',
 'delici absolut back',
 'isnt small famili restaur fine dine establish',
 'toro tartar cavier extraordinari like thinli slice wagyu white truffl',
 'dont think back long time',
 'attach ga station rare good sign',
 'awesom',
 'back mani time soon',
 'menu much good stuff could not decid',
 'wors humili worker right front mebunch horribl name call',
 'conclus fill meal',
 'daili special alway hit group',
 'tragedi struck',
 'pancak also realli good pretti larg',
 'first crawfish experi delici',
 'monster chicken fri steak egg time favorit',
 'waitress sweet funni',
 'also tast mom multigrain pumpkin pancak pecan butter amaz fluffi delici',
 'id rather eat airlin food serious',
 'cant say enough good thing place',
 'ambianc incred',
 'waitress manag friendli',
 'would not recommend place',
 'overal wasnt impress noca',
 'gyro basic lettuc',
 'terribl servic',
 'thoroughli disappoint',
 'dont much pasta love homemad hand made pasta thin pizza',
 'give tri happi',
 'far best cheesecurd ever',
 'reason price also',
 'everyth perfect night',
 'food good typic bar food',
 'drive get',
 'first glanc love bakeri cafe nice ambianc clean friendli staff',
 'anyway not think go back',
 'point finger item menu order wont disappoint',
 'oh thing beauti restaur',
 'havent gone go',
 'greasi unhealthi meal',
 'first time might last',
 'burger amaz',

In [240]:
# Step 4. Vectorization (like encoding and standardCaling):

In [241]:
# Vectorization : It converts long text data into numeric form.

# text >> numric form

# Vectorizar Type :
# 1) countvectorizar
# 2) Tokenizer(keras)
# 3) TF-ID vectorizer

In [242]:
# 1.) Count_Vectorizar :(it count the words..and it is available in sk-learn.)

In [243]:
# it is use for encoding or text convert in numeric for training .

In [244]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X = cv.fit_transform(corpus).toarray()
y= df['Liked']

In [245]:
X.shape  # in that here whatever uniqe word u have that much column we'll have.

(1395, 1613)

In [246]:
# Exlanation of above work:

#  eg.               Hi    how are  you good   by tc
# Hi how are you     1     1    1    1   0     0  0 
# are you good       0     0    1    1    1    0  0
# by by tc           0     0    0    0    0    2  1

In [247]:
y

0       1
1       0
2       0
3       1
4       1
       ..
1390    1
1391    0
1392    0
1393    0
1394    0
Name: Liked, Length: 1395, dtype: int64

In [248]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1395, 1613))

In [249]:
# Curse of dimensionality >> bcoz more feature it will confused 
# >> so we use best features only. so we use below
cv.get_feature_names_out()

array(['absolut', 'absolutley', 'accid', ..., 'yum', 'yummi', 'zero'],
      shape=(1613,), dtype=object)

In [250]:
len(cv.get_feature_names_out())

1613

In [251]:
X_df = pd.DataFrame(X,columns=cv.get_feature_names_out())

In [252]:
X_df   # here we create the 1612 columns for each uniqe word and with its count.

,absolut,absolutley,accid,accommod,accomod,accordingli,account,ach,acknowledg,across,...,yelper,yet,youd,youll,your,yucki,yukon,yum,yummi,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1390,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1391,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1392,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1393,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1394,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [253]:
# Step 5. Cross validation : (train_test_split)

In [254]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test =train_test_split(X_df,y,test_size=0.2,random_state=42)

In [255]:
# Step 6. Model Training :

In [256]:
# models for train :

# 1) naive bayes : It use for calculate probavlity of event.
#                 Multinominal bayes >> use for text data.

In [257]:
from sklearn.naive_bayes import MultinomialNB

clf=MultinomialNB()
clf.fit(X_train,y_train)

MultinomialNB()

In [258]:
clf.score(X_test,y_test)

0.8172043010752689

In [259]:
# so above MultinomialNB model we got 80% accuracy on this model.

In [260]:
# 2) Logostic Regression model :it use for descret data and calculate the  probablity.

In [261]:
from sklearn.linear_model import LogisticRegression

clf1=LogisticRegression()
clf1.fit(X_train,y_train)

LogisticRegression()

In [262]:
clf1.score(X_test,y_test)

0.8028673835125448

In [263]:
# for logistic regression we got 83% accuracy. so we use logistic regresion model.
# final model >> clf1 >> logistic regression

In [264]:
# Step 7. Prediction and Metrics :

In [265]:
y_pred= clf1.predict(X_test)

In [266]:
from sklearn.metrics import confusion_matrix,classification_report

In [267]:
print(confusion_matrix(y_test,y_pred))

[[102  27]
 [ 28 122]]

In [268]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.79      0.79       129
           1       0.82      0.81      0.82       150

    accuracy                           0.80       279
   macro avg       0.80      0.80      0.80       279
weighted avg       0.80      0.80      0.80       279

In [269]:
# Step 8. Predict New Review with model :

In [270]:
a= 'good taste'

In [271]:
# convert in list or array :

a= np.array(['not good taste'])

In [272]:
a_new =cv.transform(a).toarray()

In [273]:
a_new.shape

(1, 1613)

In [274]:
clf1.predict(a_new)

d:\ITVedant\itv-AiML_projects\Restaurant-Reviews-Predictions-With-RNN_Lstm\Project_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [275]:
# So we got 1 means good . but its not supprt to not etc.

## RNN LSTM MODEL :

# We from here we use Lstm RNN model as a solustion :

In [276]:
# Solustion for simple Model >> RNN >>LSTM/GRU.
# next advance is >> transformer.

# LSTM RNN model :

In [277]:
# Step 1. cleaning and text preprocessing :

In [278]:
df['Review']=corpus

In [279]:
# here clean the dataframe by using corpus assign.

In [280]:
df

                                                 Review  Liked
0                                        wow love place      1
1                                        crust not good      0
2                                not tasti textur nasti      0
3     stop late may bank holiday rick steve recommen...      1
4                               select menu great price      1
...                                                 ...    ...
1390                                            not bad      1
1391                                           bad tase      0
1392                                           bad food      0
1393                                           bad tast      0
1394                                        bad qualiti      0

[1395 rows x 2 columns]

In [281]:
# Here we use Tokenizer instead of vectorization in LSTM RNN to convert in numeric.
# because vectorisation is us in ML and Tokenizer use in DL-RNN,CNN ,its same to work.

In [282]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [283]:
max_words=5000
max_len=100

In [284]:
tk= Tokenizer(num_words=max_words)
tk.fit_on_texts(df['Review'])

In [285]:
# for deployment we use here pickle (to convert in numeric) :
import pickle
with open('tokenizer.pk1','wb') as f:                   #wb meanse convert in binary form
    pickle.dump(tk,f)

In [286]:
# here bcoz of pickle for deployment we use mysql,github,python 3.10,vs code.

In [287]:
# now  create  x,y. with pading:

In [288]:
X=tk.texts_to_sequences(df['Review'])

In [289]:
X=pad_sequences(X,maxlen=max_len)  # prepading (so here before rows ,cols 0 will be 
                                   #  on blanks spot.)

In [290]:
X.shape

(1395, 100)

In [291]:
X

array([[  0,   0,   0, ..., 354,  14,   3],
       [  0,   0,   0, ..., 489,   2,   5],
       [  0,   0,   0, ...,  34, 355,  82],
       ...,
       [  0,   0,   0, ...,   0,  28,   1],
       [  0,   0,   0, ...,   0,  28,  35],
       [  0,   0,   0, ...,   0,  28,  80]],
      shape=(1395, 100), dtype=int32)

In [292]:
y= df['Liked']

In [293]:
y

0       1
1       0
2       0
3       1
4       1
       ..
1390    1
1391    0
1392    0
1393    0
1394    0
Name: Liked, Length: 1395, dtype: int64

In [294]:
# step 2. Train test split :

In [295]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=42)

In [296]:
# step 3. Model Train with LSTM :

## Architecture ofLSTM layers :
1.embedding layer.
2. LSTM layer.
3.drop out layer(optional).
4.Dense layer(o/p).

In [297]:
# wow love place >> [0,0,0,.....354,14, 3]
# LSTM cannot understand raw integers directly in a meaningful way.

# why embedding layer >> It converts each word ID into a dense vector representation.

#Embedding will Captures semantic meaning
#Similar words → similar vectors
# Learns during training

In [298]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout

In [299]:
model=Sequential()
model.add(Embedding(input_dim=max_words, output_dim=128)) # it is max feture size= input_dimenstion.
model.add(LSTM(128,return_sequences=False)) # o/p dim 128 will same as lstm 128 unit of lstm 
model.add(Dropout(0.5))
model.add(Dense(1,activation='sigmoid'))

In [300]:
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [301]:
history =model.fit(
         X_train,
         y_train,
         epochs=20,
         validation_data=(X_test,y_test)
)

Epoch 1/20

35/35 ━━━━━━━━━━━━━━━━━━━━ 14s 229ms/step - accuracy: 0.5896 - loss: 0.6638 - val_accuracy: 0.5950 - val_loss: 0.6490
Epoch 2/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 199ms/step - accuracy: 0.7401 - loss: 0.5473 - val_accuracy: 0.7491 - val_loss: 0.5010
Epoch 3/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 187ms/step - accuracy: 0.8898 - loss: 0.3344 - val_accuracy: 0.7921 - val_loss: 0.4829
Epoch 4/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 187ms/step - accuracy: 0.9471 - loss: 0.1786 - val_accuracy: 0.8100 - val_loss: 0.4361
Epoch 5/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 10s 188ms/step - accuracy: 0.9633 - loss: 0.1106 - val_accuracy: 0.8029 - val_loss: 0.5447
Epoch 6/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 11s 200ms/step - accuracy: 0.9749 - loss: 0.0771 - val_accuracy: 0.8136 - val_loss: 0.5766
Epoch 7/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 192ms/step - accuracy: 0.9839 - loss: 0.0561 - val_accuracy: 0.8029 - val_loss: 0.6732
Epoch 8/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 195ms/step - accuracy: 0.9910 - loss: 0.0411 - val_accuracy: 0.7993 - val_loss: 0.7435
Epoch 9/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 186ms/step - accuracy: 0.9892 - loss: 0.0334 - val_accuracy: 0.7885 - val_loss: 0.8243
Epoch 10/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 8s 219ms/step - accuracy: 0.9884 - loss: 0.0296 - val_accuracy: 0.7957 - val_loss: 0.8282
Epoch 11/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 187ms/step - accuracy: 0.9901 - loss: 0.0280 - val_accuracy: 0.7921 - val_loss: 0.9162
Epoch 12/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 190ms/step - accuracy: 0.9910 - loss: 0.0264 - val_accuracy: 0.7957 - val_loss: 0.9185
Epoch 13/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 187ms/step - accuracy: 0.9910 - loss: 0.0214 - val_accuracy: 0.7993 - val_loss: 0.9812
Epoch 14/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 190ms/step - accuracy: 0.9928 - loss: 0.0180 - val_accuracy: 0.8029 - val_loss: 1.0394
Epoch 15/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 187ms/step - accuracy: 0.9928 - loss: 0.0213 - val_accuracy: 0.7921 - val_loss: 1.0036
Epoch 16/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 11s 204ms/step - accuracy: 0.9946 - loss: 0.0171 - val_accuracy: 0.7993 - val_loss: 1.1089
Epoch 17/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 10s 195ms/step - accuracy: 0.9919 - loss: 0.0181 - val_accuracy: 0.8029 - val_loss: 1.1440
Epoch 18/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 187ms/step - accuracy: 0.9928 - loss: 0.0168 - val_accuracy: 0.7921 - val_loss: 1.1286
Epoch 19/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 11s 190ms/step - accuracy: 0.9946 - loss: 0.0147 - val_accuracy: 0.7921 - val_loss: 1.1069
Epoch 20/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 10s 284ms/step - accuracy: 0.9955 - loss: 0.0157 - val_accuracy: 0.7957 - val_loss: 1.1608

In [302]:
# so we got val_accuracy =83 % and accuracy is 99%.

In [303]:
#Step 4. Check Test accuracy :

In [304]:
loss,accuracy= model.evaluate(X_test,y_test)
print("Test Accuracy:",accuracy)

9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - accuracy: 0.7957 - loss: 1.1608
Test Accuracy: 0.7956989407539368

In [305]:
# we dont have long data model ,so now we train new model on whole data not only train data for better accurcy:
history =model.fit(
         X,
         y,
         epochs=27,
         batch_size=32)

Epoch 1/27

44/44 ━━━━━━━━━━━━━━━━━━━━ 10s 212ms/step - accuracy: 0.9491 - loss: 0.1825
Epoch 2/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 178ms/step - accuracy: 0.9828 - loss: 0.0645
Epoch 3/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 9s 206ms/step - accuracy: 0.9900 - loss: 0.0331
Epoch 4/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 187ms/step - accuracy: 0.9957 - loss: 0.0202
Epoch 5/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - accuracy: 0.9964 - loss: 0.0152
Epoch 6/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 11s 187ms/step - accuracy: 0.9950 - loss: 0.0156
Epoch 7/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 10s 177ms/step - accuracy: 0.9950 - loss: 0.0145
Epoch 8/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 170ms/step - accuracy: 0.9957 - loss: 0.0120
Epoch 9/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 184ms/step - accuracy: 0.9950 - loss: 0.0112
Epoch 10/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 10s 178ms/step - accuracy: 0.9978 - loss: 0.0102
Epoch 11/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 9s 203ms/step - accuracy: 0.9986 - loss: 0.0080
Epoch 12/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step - accuracy: 0.9971 - loss: 0.0089
Epoch 13/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - accuracy: 0.9950 - loss: 0.0091
Epoch 14/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 181ms/step - accuracy: 0.9978 - loss: 0.0086
Epoch 15/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - accuracy: 0.9986 - loss: 0.0070
Epoch 16/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 11s 196ms/step - accuracy: 0.9971 - loss: 0.0075
Epoch 17/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 11s 206ms/step - accuracy: 0.9978 - loss: 0.0083
Epoch 18/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 10s 183ms/step - accuracy: 0.9964 - loss: 0.0069
Epoch 19/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 10s 177ms/step - accuracy: 0.9978 - loss: 0.0074
Epoch 20/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 11s 177ms/step - accuracy: 0.9986 - loss: 0.0056
Epoch 21/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - accuracy: 0.9964 - loss: 0.0057
Epoch 22/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 10s 172ms/step - accuracy: 0.9986 - loss: 0.0044
Epoch 23/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 187ms/step - accuracy: 0.9978 - loss: 0.0073
Epoch 24/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 10s 176ms/step - accuracy: 0.9950 - loss: 0.0099
Epoch 25/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 10s 175ms/step - accuracy: 0.9957 - loss: 0.0147
Epoch 26/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 190ms/step - accuracy: 0.9964 - loss: 0.0137
Epoch 27/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - accuracy: 0.9964 - loss: 0.0109

In [306]:
# Step 5. Predict the model: and check Metrics :

In [307]:
y_pred=model.predict(X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 153ms/step

In [308]:
y_pred1=[ 1 if i>0.5 else 0 for i in y_pred]

In [309]:
# check metrics:
from sklearn.metrics import confusion_matrix,classification_report

In [310]:
confusion_matrix(y_test,y_pred1)

array([[129,   0],
       [  0, 150]])

In [311]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       129
           1       1.00      1.00      1.00       150

    accuracy                           1.00       279
   macro avg       1.00      1.00      1.00       279
weighted avg       1.00      1.00      1.00       279

In [312]:
# step 6. Save the model :

In [313]:
model.save('Lstm_resturant_review_pred.keras')

In [314]:
# Step 6. Predict the new Review :

In [315]:
# By Using LSTM Predict.

In [316]:
a = 'good taste'

In [317]:
def predict_text(text):
    text = text.lower()
    seq = tk.texts_to_sequences([text])
    padded= pad_sequences(seq,maxlen=max_len)
    pred = model.predict(padded)[0][0]

    if pred > 0.5:
        return f"positive ({pred:.2f})"
    else:
        return f"Negative ({pred:.2f})"

In [326]:
# then call the pred fun:

predict_text('bad food ')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 205ms/step

'Negative (0.05)'

In [327]:
# good taste >> 1
# bad food >> 0
# not bad >> 1
# not good >> 0